// SPDX-License-Identifier: MIT
pragma solidity ^0.8.17;

// Immutable variables are like constants. Values of immutable
// variables can be set inside the constructor but cannot be
// modified afterwards.

// https://docs.soliditylang.org/en/v0.8.19/contracts.html#immutable
// The contract creation code generated by the compiler will
// modify the contract’s runtime code before it is returned
// by replacing all references to immutables with the values
// assigned to them. This is important if you are comparing
// the runtime code generated by the compiler with the one
// actually stored in the blockchain.
contract Immutable {
    // coding convention to uppercase constant variables
    address public immutable MY_ADDRESS;
    uint public immutable MY_UINT;

    constructor(uint _myUint) {
        MY_ADDRESS = msg.sender;
        MY_UINT = _myUint;
    }
}
